<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="mdt._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="sweetalert2.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        function ShowProgress() {
            setTimeout(function () {
                var modal = $('<div />');
                modal.addClass("modal");
                $('body').append(modal);
                var loading = $(".loading");
                loading.show();
                var top = Math.max($(window).height() / 2 - loading[0].offsetHeight / 2, 0);
                var left = Math.max($(window).width() / 2 - loading[0].offsetWidth / 2, 0);
                loading.css({ top: top, left: left });
            }, 200);
        }
        $('form').live("submit", function () {
            ShowProgress();
        });
    </script>
    <link rel="stylesheet" href="sweetalert2.min.css">
    <style type="text/css">
    .modal
    {
        position: fixed;
        top: 0;
        left: 0;
        background-color: black;
        z-index: 99;
        opacity: 0.8;
        filter: alpha(opacity=80);
        -moz-opacity: 0.8;
        min-height: 100%;
        width: 100%;
    }
    .loading
    {
        font-family: Arial;
        font-size: 10pt;
        border: 5px solid #67CFF5;
        width: 200px;
        height: 100px;
        display: none;
        position: fixed;
        background-color: White;
        z-index: 999;
    }
    </style>

    <div class="jumbotron">
        <p>Prestaged Devices List</p>
        
           <div>
              <asp:GridView ID="GridView1" runat="server" OnRowDeleting="OnRowDeleting" AutoGenerateDeleteButton="True" Width="100%" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
              </asp:GridView>
               <br />
               <table style="width: 100%;">
                   <tr><td style="width: 30%;"><asp:Button ID="ListButton" runat="server" OnClick="ListButton_Click" Text="Device List" /><p></p></td></tr>
                     <tr>
                   <td style="width: 30%;">Add Device</td>
                       <td></td>                    
                   </tr>
                   <tr>
                       <td style="width: 30%;">Barcode Label</td>
                       <td>   
                           <asp:TextBox ID="txt_Barcode" runat="server" TextMode="SingleLine" Width="300px" MaxLength="5"></asp:TextBox> &ensp; (Format: 01234)
                       </td>
                   </tr>
                   <tr>
                       <td style="width: 30%">Service Tag</td>
                       <td>
                           <asp:TextBox ID="txt_ServiceTag" runat="server" TextMode="SingleLine" Width="300px" MaxLength="7"></asp:TextBox> &ensp; (Format: ABCD123)
                       </td>
                   </tr>
                   <tr>
                       <td style="width: 30%">Mac Address</td>
                       <td>
                           <asp:TextBox ID="txt_MacAddress" runat="server" TextMode="SingleLine" Width="300px" MaxLength="17"></asp:TextBox> &ensp; (Format: AA-BB-CC-DD-EE-FF)
                       </td>
                   </tr>
                   <tr>
                       <td style="width: 30%">Model</td>
                       <td>
                           <asp:DropDownList ID="lst_Model" runat="server" Width="300px">
                           </asp:DropDownList>
                       </td>
                   </tr>
                   <tr>
                       <td style="width: 30%">Type</td>
                       <td>
                           <asp:DropDownList ID="lst_Type" runat="server" Width="300px">
                           </asp:DropDownList>
                       </td>
                   </tr>
                   <tr>
                       <td style="width: 30%">&nbsp;</td>
                       <td>
                           <asp:CheckBox ID="chk_Software" runat="server" Text="Install Std Build Software" /> &ensp; <asp:CheckBox ID="chk_Activation" runat="server" Text="Activation After MDT" />
                       </td>
                   </tr>
                   <tr>
                       <td style="width: 30%">&nbsp;</td>
                       <td>
                           &nbsp;</td>
                   </tr>
                    <tr>
                       <td style="width: 30%"></td>
                       <td>
                           <asp:Button ID="AddButton" runat="server" OnClick="AddButton_Click" Text="Add Device" /> &ensp;
                           <asp:Button ID="ResetButton" runat="server" OnClick="ResetButton_Click" Text="Reset" />
                       </td>
                   </tr>
               </table>
              </div>

        <div>
            <p></p>
            MPSC Standard Build Software List<br />
              <asp:TextBox ID="txt_SoftwareList" runat="server" Height="100px" Width="500px" TextMode="MultiLine" Wrap="False"></asp:TextBox>
           <p></p>
            Activation List<br />
            <asp:TextBox ID="txt_ActivationList" runat="server" Height="100px" Width="500px" TextMode="MultiLine" Wrap="False"></asp:TextBox>
           <p></p>
            Debug<br />
            <asp:TextBox ID="TextBox1" runat="server" Height="100px" Width="500px" TextMode="MultiLine" Wrap="False"></asp:TextBox>
        </div>
    </div>
    <div class="loading" align="center">Loading. Please wait.<br />
    <br />
    <img src="images/loader.gif" width="40" height="40" alt="" />
    </div>

</asp:Content>
